version: "3.1"
services:
  ssr_client:
#    build: .
    image: lyekumchew/ssr_client
    volumes:
      - ./config.json:/etc/shadowsocksr/shadowsocks/config.json
    ports:
      - 127.0.0.1:1080:1080
    restart: always
